Repository TheHotMessExpress/recipe-finder, pull requests merged in 2023-03, with the labels that each got.

#19 Camden jesse add homepage design
  frontend/recipeapp/src/images/Camden.jpg
  frontend/recipeapp/src/images/andrew.png
  frontend/recipeapp/src/images/goofy.webp
  frontend/recipeapp/src/images/jesse.jpg
  frontend/recipeapp/src/images/miranda.jpg
  frontend/recipeapp/src/index.css
  frontend/recipeapp/src/pages/Home.js
  package-lock.json
  package.json
Labels: enhancement

#29 Andrew miranda add user login
  backend/functions/func_users.php
  backend/login.php
  frontend/recipeapp/src/pages/Login.js
  frontend/recipeapp/src/pages/Navigation.js
  frontend/recipeapp/src/pages/Register.js
Labels: sprint-3

#28 feat: Add search dietary filtering
  backend/functions/func_recipes.php
  backend/search_recipes.php
  frontend/recipeapp/src/index.css
  frontend/recipeapp/src/pages/FoodSearch.js
Labels: enhancement, sprint-3
